name: test

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.5
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: test
        run: go test
